Update platform-channels.md
Fix issues with wrong argument in 'MainActivity.java'

Some conflict when using import `io.flutter.embedding.android.FlutterActivity;` 

> error: incompatible types: FlutterEngine cannot be converted to PluginRegistry