Fix: FlutterEngine cannot be converted to PluginRegistry
Fix issues with wrong argument in 'MainActivity.java'

> error: incompatible types: FlutterEngine cannot be converted to PluginRegistry