TimelineSummary requires 'new' keyword
TimelineSummary summary = TimelineSummary.summarize(timeline); causes the following error:

NoSuchMethodError: No static method 'summarize' declared in class 'TimelineSummary'.

Adding the 'new' keyword fixes this:

TimelineSummary summary = new TimelineSummary.summarize(timeline);

Flutter version tested:
Flutter 0.5.1 • channel beta • git@github.com:flutter/flutter.git
Framework • revision c7ea3ca377 (3 months ago) • 2018-05-29 21:07:33 +0200
Engine • revision 1ed25ca7b7
Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760